version: "3.8"

networks:
  tinder_clone_backend_springboot-mysql-net:

services:
  mysqldb:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      tinder_clone_backend_springboot-mysql-net:
  app:
    depends_on:
      - mysqldb
    networks:
      tinder_clone_backend_springboot-mysql-net:
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mydatabase?useSSL=false
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
